### PR TITLE
Fix Dupe Glitch Involving Plastics

### LINKED ISSUE #1506: you can make a pbi block out of one pbi pulp
### Nomi CEu Version

1.7.7

### Launcher

prism

### Configurations or Mods Changed

zbgt, ae2fcr

### Environment

singleplayer

### Mode

Normal Mode

### What Happened

There is an extruder recipe to turn 1 pbi pulp into a pbi block, which can be turned into 9 pulp. I doubt that was intended since it lets you make infinite pbi out of a single pulp

### Expected Behavior

Recipe should be 9 pbi pulp for a pbi block

### Reproduction Steps

check recipe for pbi block in jei in extruder

### Logs

_No response_

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by v3ect0rgames**
Fixes #1506 

All pulps can be turned from 1 pulp to 1 block to 9 pulp and repeat to dupe.

Fixes by making the recipe 9 pulp for block.

### CODE REVIEW

File: overrides/groovy/post/main/general/misc/qol/pulps.groovy [hunk 1]
```diff
@@ -38,7 +38,7 @@ for (var material : materials) {
         mods.gregtech.extruder.changeByOutput([stack], null)
             .forEach { ChangeRecipeBuilder builder ->
                 builder.changeInput(0) {
-                    new GTRecipeItemInput(dust)
+                    new GTRecipeItemInput(dust * 9)
```
Comment (IntegerLimit) [inline overrides/groovy/post/main/general/misc/qol/pulps.groovy]:
```suggestion
                    new GTRecipeItemInput(dust, it.amount)
```

File: overrides/groovy/post/main/general/misc/qol/pulps.groovy [hunk 2]
```diff
@@ -38,7 +38,7 @@ for (var material : materials) {
         mods.gregtech.extruder.changeByOutput([stack], null)
             .forEach { ChangeRecipeBuilder builder ->
                 builder.changeInput(0) {
```
Comment (IntegerLimit) [inline overrides/groovy/post/main/general/misc/qol/pulps.groovy]:
```suggestion
                builder.changeInput(0) { GTRecipeInput input ->
```

File: overrides/groovy/post/main/general/misc/qol/pulps.groovy [hunk 3]
```diff
@@ -38,7 +38,7 @@ for (var material : materials) {
...
-                    new GTRecipeItemInput(dust)
+                    new GTRecipeItemInput(dust, it.amount)
```
Comment (IntegerLimit) [inline overrides/groovy/post/main/general/misc/qol/pulps.groovy]:
```suggestion
                    new GTRecipeItemInput(dust, input.amount)
```

**Review by IntegerLimit — CHANGES_REQUESTED** [review]
You need to fix the groovy lint issue. Apply **all three** suggested changes to do this.

Technically, you could make the closure parameter be named `it`, preventing the need for the second change, but if we are going to have an explicit parameter we might as well give it a descriptive name.

File: overrides/groovy/post/main/general/misc/qol/pulps.groovy
Comment (IntegerLimit) [inline overrides/groovy/post/main/general/misc/qol/pulps.groovy:9]:
```suggestion
import gregtech.api.recipes.ingredients.GTRecipeInput
import gregtech.api.recipes.ingredients.GTRecipeItemInput
```
